### ISSUE TITLE
커스텀 예외 생성

### ISSUE THREAD

**Issue by sudago** [max2023-4th-project-01/BE-B-Cokkiri-Market#27]
## TODO
- [x] ErrorCode - 인터페이스
- [x] CustomException - 커스텀 예외
- [x] ErrorResponse - 해당 Response로 감싸서 반환
- [x] GlobalExceptionHandler - 에러만 관리. Controller 역할
    - [x] `@RestControllerAdvice`
    - [x] `@ExceptionHandler`

## 기타
- detail 추가
    - 개발 시 정확한 오류 원인을 파악하기 위해서 custom message와 함께 error message를 반환.
    (Custom Exception은 custom message 하나만 존재해도 파악 가능하므로 제외)
