### ISSUE TITLE
BE용 CI/CD 환경 설정

### ISSUE THREAD

**Issue by sudago** [max2023-4th-project-01/BE-B-Cokkiri-Market#7]
## TODO
CI/CD
- [x] github actions 스크립트 작성
- [x] docker를 이용한 인스턴스 생성 스크립트 작성
- [x] local 설정
    - [x] docker image 생성/버전 추가
- [x] AWS
    - [x] ec2, rds, s3 생성
    - [x] ec2
        - [x] docker, docker-compose 설치
    - [x] ec2 도커
        - [x] image 다운/업데이트
        - [x] container 실행 (spring boot, react, nginx)

## 기타
<--필요할 경우 적어주세요-->
